
language: cpp

sudo: required

services:
    - docker

before_install:
- docker pull dbeurle/neon
- docker build dbeurle/neon

script:
- docker run -it dbeurle/neon /bin/bash && /app/neon/build/ctest
