language: cpp
sudo: required
services:
    - docker
env:
    - BUILD_TYPE=RelWithDebInfo
    - BUILD_TYPE=Release
    - BUILD_TYPE=Debug
before_install:
    # Encrypted key setup
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_3bf24bb6ee14_key -iv $encrypted_3bf24bb6ee14_iv -in travisci_rsa.enc -out travisci_rsa -d;
    chmod 0600 travisci_rsa;
    cp travisci_rsa ~/.ssh/id_rsa;
    fi'
    # Build docker image
    - docker build -t neon .
script:
    - docker run -e TRAVIS=$TRAVIS -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID --name neon-docker -d -t neon /bin/bash
    - docker exec neon-docker /bin/bash -c "mkdir -p neon/build && cd neon/build && cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE .. && make all -j2"
    - docker exec neon-docker /bin/bash -c "cd neon/build && make install && ctest -j2 --output-on-failure"
after_success:
    # Coverage
    - docker exec neon-docker /bin/bash -c "pip install cpp-coveralls"
    - docker exec neon-docker /bin/bash -c "cd neon/build && make coverage && make install"
    - docker exec neon-docker /bin/bash -c "cd neon/build && cpp-coveralls --lcov-file=coverage.info --no-gcov"
