
language: cpp

sudo: required
dist: trusty

compiler: clang

matrix:
    include:
        # works on Trusty
        - os: linux
          addons:
            apt:
              sources:
                - llvm-toolchain-trusty-4.0
              packages:
                - clang-4.0
          env:
            - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

        # works on Trusty
        - os: linux
          addons:
            apt:
              sources:
                - llvm-toolchain-trusty
              packages:
                - clang-5.0
          env:
            - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"
addons:
    apt:
        sources:
            - george-edison55-precise-backports
        packages:
            - cmake-data
            - cmake
