language: cpp
sudo: required
before_install:
  - openssl aes-256-cbc -K $encrypted_3bf24bb6ee14_key -iv $encrypted_3bf24bb6ee14_iv -in travisci_rsa.enc -out travisci_rsa -d
  - chmod 0600 travisci_rsa
  - cp travisci_rsa ~/.ssh/id_rsa
script:
- sudo apt-get install --yes doxygen graphviz
- mkdir -p docs/html
- git clone -b gh-pages git@github.com:dbeurle/neon.git --single-branch docs/html
- cd docs/html
- git rm -rf && cd ..
- doxygen
- cd html && git add . && git commit -m "Automated documentation build"
- git push origin gh-pages
