language: cpp
sudo: required
services:
    - docker
before_install:
    - openssl aes-256-cbc -K $encrypted_3bf24bb6ee14_key -iv $encrypted_3bf24bb6ee14_iv -in travisci_rsa.enc -out travisci_rsa -d
    - chmod 0600 travisci_rsa
    - cp travisci_rsa ~/.ssh/id_rsa
    - docker build -t neon .
script:
    - docker run -e TRAVIS=$TRAVIS -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID --name neon-docker -d -t neon /bin/bash
    - docker exec neon-docker /bin/bash -c "cd neon && mkdir build && cd build && cmake -DENABLE_COVERAGE=TRUE .. && make all -j4 && ctest"
after_success:
    - docker exec neon-docker /bin/bash -c "pip install cpp-coveralls"
    - docker exec neon-docker /bin/bash -c "cd neon/build && make coverage"
    - docker exec neon-docker /bin/bash -c "cd neon/build && cpp-coveralls --lcov-file=coverage.info --no-gcov"
    - sudo apt-get install --yes doxygen graphviz
    - mkdir -p docs/html
    - git clone -b gh-pages git@github.com:dbeurle/neon.git --single-branch docs/html
    - cd docs/html
    - git rm -rf . && cd ..
    - doxygen
    - cd html
    - git add .
    - git commit -m "Automated documentation build"
    - git push origin gh-pages
