
language: cpp

sudo: required

services:
    - docker

before_install:
- ls
- cd dbeurle/neon
- docker build -t neon .

script:
- docker run -it neon /bin/bash -c "cd neon && mkdir build && cd build && cmake .. && make all -j4 && ctest"
