
language: cpp

sudo: required

compiler:
  - clang

matrix:
    include:
        - os: linux
          addons:
            apt:
              sources:
                - llvm-toolchain-trusty-4.0
              packages:
                - clang-4.0
          env:
              - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"

        # - os: linux
        #   addons:
        #     apt:
        #       sources:
        #           - llvm-toolchain-trusty
        #       packages:
        #           - clang-5.0
        #   env:
        #     - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libvtk6-dev libboost-all-dev -y
  - eval "${MATRIX_EVAL}"

addons:
    apt:
        sources:
            - george-edison55-precise-backports
        packages:
            - cmake-data
            - cmake

before_script:
    - eval "${MATRIX_EVAL}"
    - mkdir build
    - cd build
    - cmake ..
