
language: cpp

sudo: required

services:
    - docker

before_install:
    - pip install --user coveralls
    - docker build -t neon .

script:
    - docker run -d -t neon /bin/bash -c "cd neon && mkdir build && cd build && cmake .. && make all -j4 && ctest"

after_success:
    - docker ps
    - docker cp
    - pwd
    - ls
    - cd ..
    - if [[ "$CXX" =~ ^g.* ]]; then coveralls --gcov-options '\-lp'; fi
