
language: cpp

sudo: required

services:
    - docker

before_install:
    - pip install --user cpp-coveralls
    - docker build -t neon .

script:
    # Initialise the docker container and use exec to drive it
    - docker run --name neon-docker -d -t neon /bin/bash
    - docker exec neon-docker /bin/bash -c "cd neon && mkdir build && cd build && cmake -DENABLE_COVERAGE=TRUE .. && make all -j4 && ctest"

after_success:
    - docker exec neon-docker /bin/bash -c "cd neon/build && make coverage"
    - docker cp neon-docker:/app/neon/build/coverage.info .
    - docker cp neon-docker:/app/neon/build/coverage_output .
    - ls coverage_output
    - coveralls --gcov-options '\-lp'
